[project]
name = "zerolink"
version = "0.10.1"
description = "one-step rclone and symlink folders"
requires-python = ">=3.10,<3.11"
dependencies = [
]

[project.scripts]
zerolink = "zerolink.__main__:run"

[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["zerolink*"]
exclude = ["zerolink.pylint_custom*"] # Exclude local pylint plugins from distribution

[dependency-groups]
dev = [
    "pylint>=3.3.8",
    "pyinstaller>=6.15.0",
]
